/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.ClienteDAO;
import dao.FuncionarioDAO;
import controler.FuncoesUteis;
import java.math.BigDecimal;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Endereco;
import model.Funcionario;

/**
 *
 * @author lucas
 */
public class DialogCadPessoa extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogCadPessoa.class.getName());
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/uuuu")
            .withResolverStyle(ResolverStyle.STRICT);
    private final ClienteDAO clienteDAO = new ClienteDAO();
    private final FuncionarioDAO funcionarioDAO = new FuncionarioDAO();

    /**
     * Creates new form DialogCadCliente
     */
    public DialogCadPessoa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configurarSelecaoTipoPessoa();
        btnSalvar.addActionListener(evt -> btnSalvarActionPerformed(evt));
        btnLimpar.addActionListener(evt -> btnLimparActionPerformed(evt));
        btnCancelar.addActionListener(evt -> btnCancelarActionPerformed(evt));
        bloquearEndereco(true);
        txtCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscarEnderecoPorCep();
            }
        });
    }

    private void configurarSelecaoTipoPessoa() {
        if (!RBCliente.isSelected() && !RBFuncionario.isSelected()) {
            RBCliente.setSelected(true);
        }
        RBCliente.addActionListener(evt -> atualizarCamposFuncionario());
        RBFuncionario.addActionListener(evt -> atualizarCamposFuncionario());
        atualizarCamposFuncionario();
    }

    private void atualizarCamposFuncionario() {
        boolean funcionario = isFuncionarioSelecionado();
        labelCargo.setEnabled(funcionario);
        jLabel1.setEnabled(funcionario);
        jTextField1.setEnabled(funcionario);
        jFormattedTextField1.setEnabled(funcionario);
        panelCadCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(funcionario ? "Cad. Funcionario" : "Cad. Cliente"));
    }

    private boolean isFuncionarioSelecionado() {
        return RBFuncionario.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTPessoa = new javax.swing.ButtonGroup();
        panelCadCliente = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        labelDtNasc = new javax.swing.JLabel();
        txtDtNasc = new javax.swing.JFormattedTextField();
        panelEndereco = new javax.swing.JPanel();
        labelCEP = new javax.swing.JLabel();
        txtCEP = new javax.swing.JFormattedTextField();
        labelRua = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        labelBairro = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        labelUF = new javax.swing.JLabel();
        cmbUF = new javax.swing.JComboBox<>();
        labelCidade = new javax.swing.JLabel();
        cmbCidade = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panelContato = new javax.swing.JPanel();
        labelTel = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        RBCliente = new javax.swing.JRadioButton();
        RBFuncionario = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        labelCargo = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelCadCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Cad. Cliente"));

        labelNome.setText("Nome:");

        labelCPF.setText("CPF:");

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        labelDtNasc.setText("Dt. Nasc:");

        try {
            txtDtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        panelEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        labelCEP.setText("CEP:");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## ###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });

        labelRua.setText("Rua:");

        txtRua.setToolTipText("");
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });

        labelBairro.setText("Bairro:");

        labelUF.setText("UF:");

        cmbUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelCidade.setText("Cidade:");

        cmbCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelEnderecoLayout = new javax.swing.GroupLayout(panelEndereco);
        panelEndereco.setLayout(panelEnderecoLayout);
        panelEnderecoLayout.setHorizontalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addComponent(labelCEP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEnderecoLayout.createSequentialGroup()
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelEnderecoLayout.createSequentialGroup()
                                .addComponent(labelUF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbUF, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelEnderecoLayout.createSequentialGroup()
                                .addComponent(labelRua)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBairro)
                            .addComponent(labelCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBairro)
                            .addComponent(cmbCidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(6, 6, 6))
        );
        panelEnderecoLayout.setVerticalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCEP)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRua)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBairro)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelUF)
                    .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelCidade)
                        .addComponent(cmbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 24, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");

        btnLimpar.setText("Limpar");

        btnCancelar.setText("Cancelar");

        panelContato.setBorder(javax.swing.BorderFactory.createTitledBorder("Contatos"));

        labelTel.setText("Tel.");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelContatoLayout = new javax.swing.GroupLayout(panelContato);
        panelContato.setLayout(panelContatoLayout);
        panelContatoLayout.setHorizontalGroup(
            panelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContatoLayout.createSequentialGroup()
                .addComponent(labelTel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelContatoLayout.setVerticalGroup(
            panelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTel)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Pessoa"));

        groupTPessoa.add(RBCliente);
        RBCliente.setText("Cliente");
        RBCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBClienteActionPerformed(evt);
            }
        });

        groupTPessoa.add(RBFuncionario);
        RBFuncionario.setText("Funcionário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(RBCliente)
                .addGap(18, 18, 18)
                .addComponent(RBFuncionario)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBCliente)
                    .addComponent(RBFuncionario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Para Funcionário"));

        labelCargo.setText("Cargo");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Salário R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(labelCargo)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCargo)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelCadClienteLayout = new javax.swing.GroupLayout(panelCadCliente);
        panelCadCliente.setLayout(panelCadClienteLayout);
        panelCadClienteLayout.setHorizontalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCadClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelCPF)
                                    .addComponent(labelNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelDtNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelCadClienteLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addGroup(panelCadClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panelContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCadClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadClienteLayout.setVerticalGroup(
            panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCPF)
                    .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDtNasc)
                        .addComponent(txtDtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCadClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloquearEndereco(boolean bloqueado) {
        txtRua.setEnabled(!bloqueado);
        txtBairro.setEnabled(!bloqueado);
        cmbUF.setEnabled(!bloqueado);
        cmbCidade.setEnabled(!bloqueado);
    }

    private void limparCamposEndereco() {
        txtRua.setText("");
        txtBairro.setText("");
        cmbUF.setSelectedItem(null);
        cmbCidade.setSelectedItem(null);
    }

    private void preencherCamposEndereco(Endereco endereco) {
        txtRua.setText(endereco.getRua() == null ? "" : endereco.getRua());
        txtBairro.setText(endereco.getBairro() == null ? "" : endereco.getBairro());
        setComboValue(cmbUF, endereco.getUf());
        setComboValue(cmbCidade, endereco.getCidade());
    }

    private void setComboValue(javax.swing.JComboBox<String> combo, String value) {
        if (value == null || value.trim().isEmpty()) {
            combo.setSelectedItem(null);
            return;
        }

        String normalized = value.trim();
        ComboBoxModel<String> model = combo.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            String item = model.getElementAt(i);
            if (item != null && item.equalsIgnoreCase(normalized)) {
                combo.setSelectedItem(item);
                return;
            }
        }

        combo.addItem(normalized);
        combo.setSelectedItem(normalized);
    }

    private void buscarEnderecoPorCep() {
        final String cepLimpo = txtCEP.getText() == null
                ? ""
                : txtCEP.getText().replaceAll("\\D", "");
        if (cepLimpo.length() != 8) {
            limparCamposEndereco();
            bloquearEndereco(true);
            return;
        }

        bloquearEndereco(true);

        javax.swing.SwingWorker<Endereco, Void> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Endereco doInBackground() {
                try {
                    return FuncoesUteis.consultaCep(cepLimpo);
                } catch (IOException ex) {
                    logger.log(Level.WARNING, "Falha ao consultar CEP: " + cepLimpo, ex);
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    Endereco endereco = get();
                    if (endereco == null) {
                        limparCamposEndereco();
                        bloquearEndereco(false);
                        return;
                    }
                    preencherCamposEndereco(endereco);
                    bloquearEndereco(true);
                } catch (InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    logger.log(Level.WARNING, "Consulta de CEP interrompida: " + cepLimpo, ex);
                    limparCamposEndereco();
                    bloquearEndereco(false);
                } catch (ExecutionException ex) {
                    logger.log(Level.WARNING, "Falha ao processar consulta de CEP: " + cepLimpo, ex);
                    limparCamposEndereco();
                    bloquearEndereco(false);
                }
            }
        };

        worker.execute();
    }

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        buscarEnderecoPorCep();
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void RBClienteActionPerformed(java.awt.event.ActionEvent evt) {
        atualizarCamposFuncionario();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Campo de cargo.
    }

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNome.getText() == null ? "" : txtNome.getText().trim();
        String cpf = onlyDigits(txtCPF.getText());
        String telefone = onlyDigits(txtTelefone.getText());
        LocalDate dtNasc = parseDataNascimento(txtDtNasc.getText());
        String cep = onlyDigits(txtCEP.getText());
        String rua = txtRua.getText() == null ? "" : txtRua.getText().trim();
        String bairro = txtBairro.getText() == null ? "" : txtBairro.getText().trim();
        String cidade = getComboValue(cmbCidade);
        String uf = getComboValue(cmbUF);
        boolean funcionarioSelecionado = isFuncionarioSelecionado();
        String cargo = jTextField1.getText() == null ? "" : jTextField1.getText().trim();
        BigDecimal salario = funcionarioSelecionado ? parseBigDecimal(jFormattedTextField1.getText()) : null;

        List<String> erros = validarCamposCliente(nome, cpf, telefone, dtNasc, cep, rua, bairro, cidade, uf);
        if (funcionarioSelecionado) {
            if (cargo.isEmpty()) {
                erros.add("Informe o cargo.");
            }
            if (salario == null || salario.compareTo(BigDecimal.ZERO) < 0) {
                erros.add("Informe um salario valido.");
            }
        }
        if (!erros.isEmpty()) {
            JOptionPane.showMessageDialog(this, String.join("\n", erros));
            return;
        }

        Endereco endereco = new Endereco();
        endereco.setCep(cep);
        endereco.setRua(rua);
        endereco.setBairro(bairro);
        endereco.setCidade(cidade);
        endereco.setUf(uf);

        try {
            if (funcionarioSelecionado) {
                Funcionario funcionario = new Funcionario();
                funcionario.setNome(nome);
                funcionario.setTelefone(telefone);
                funcionario.setCpf(cpf);
                funcionario.setDtNasc(dtNasc);
                funcionario.setEndereco(endereco);
                funcionario.setCargo(cargo);
                funcionario.setSalario(salario);
                funcionarioDAO.salvar(funcionario);
                JOptionPane.showMessageDialog(this, "Funcionario salvo com sucesso.");
            } else {
                Cliente cliente = new Cliente();
                cliente.setNome(nome);
                cliente.setTelefone(telefone);
                cliente.setCpf(cpf);
                cliente.setDtNasc(dtNasc);
                cliente.setEndereco(endereco);
                clienteDAO.salvar(cliente);
                JOptionPane.showMessageDialog(this, "Cliente salvo com sucesso.");
            }
            limparCamposCliente();
            bloquearEndereco(true);
        } catch (RuntimeException ex) {
            logger.log(Level.SEVERE, "Falha ao salvar pessoa", ex);
            JOptionPane.showMessageDialog(this, "Falha ao salvar pessoa: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCamposCliente();
        bloquearEndereco(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limparCamposCliente() {
        txtNome.setText("");
        txtCPF.setValue(null);
        txtDtNasc.setValue(null);
        txtTelefone.setValue(null);
        txtCEP.setValue(null);
        limparCamposEndereco();
        jTextField1.setText("");
        jFormattedTextField1.setText("R$");
        RBCliente.setSelected(true);
        atualizarCamposFuncionario();
    }

    private String getComboValue(javax.swing.JComboBox<String> combo) {
        Object selected = combo.getSelectedItem();
        if (selected == null) {
            return "";
        }
        String value = selected.toString().trim();
        if (value.isEmpty() || value.toLowerCase().startsWith("item")) {
            return "";
        }
        return value;
    }

    private List<String> validarCamposCliente(String nome,
            String cpf,
            String telefone,
            LocalDate dtNasc,
            String cep,
            String rua,
            String bairro,
            String cidade,
            String uf) {
        List<String> erros = new ArrayList<>();

        if (nome.isEmpty()) {
            erros.add("Informe o nome.");
        }
        if (cpf.length() != 11) {
            erros.add("Informe um CPF valido.");
        }
        if (dtNasc == null) {
            erros.add("Informe uma data de nascimento valida.");
        }
        if (telefone.length() < 10 || telefone.length() > 11) {
            erros.add("Informe um telefone valido.");
        }
        if (cep.length() != 8) {
            erros.add("Informe um CEP valido.");
        }
        if (rua.isEmpty()) {
            erros.add("Informe a rua.");
        }
        if (bairro.isEmpty()) {
            erros.add("Informe o bairro.");
        }
        if (cidade.isEmpty()) {
            erros.add("Informe a cidade.");
        }
        if (uf.isEmpty()) {
            erros.add("Informe a UF.");
        }

        return erros;
    }

    private LocalDate parseDataNascimento(String rawValue) {
        String normalized = rawValue == null ? "" : rawValue.trim();
        if (onlyDigits(normalized).isEmpty()) {
            return null;
        }
        try {
            return LocalDate.parse(normalized, DATE_FORMATTER);
        } catch (DateTimeParseException ex) {
            return null;
        }
    }

    private String onlyDigits(String value) {
        return value == null ? "" : value.replaceAll("\\D", "");
    }


    private BigDecimal parseBigDecimal(String value) {
        String text = value == null ? "" : value.trim();
        if (text.isEmpty()) {
            return null;
        }
        String normalized = text.replace(" ", "");
        if (normalized.contains(",") && normalized.contains(".")) {
            normalized = normalized.replace(".", "").replace(",", ".");
        } else {
            normalized = normalized.replace(",", ".");
        }
        try {
            return new BigDecimal(normalized);
        } catch (NumberFormatException ex) {
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBCliente;
    private javax.swing.JRadioButton RBFuncionario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCidade;
    private javax.swing.JComboBox<String> cmbUF;
    private javax.swing.ButtonGroup groupTPessoa;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelBairro;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelCargo;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelDtNasc;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelRua;
    private javax.swing.JLabel labelTel;
    private javax.swing.JLabel labelUF;
    private javax.swing.JPanel panelCadCliente;
    private javax.swing.JPanel panelContato;
    private javax.swing.JPanel panelEndereco;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JFormattedTextField txtDtNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRua;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
