/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.CategoriaDAO;
import dao.FornecedorDAO;
import dao.ProdutoDAO;
import java.util.List;
import java.util.logging.Level;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Categoria;
import model.Fornecedor;
import model.Produto;

/**
 *
 * @author 2024122760121
 */
public class DialogCadProduto extends javax.swing.JDialog {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogCadProduto.class.getName());
    private static final String CATEGORIA_OUTRO = "Outro";
    private final CategoriaDAO categoriaDAO = new CategoriaDAO();
    private final ProdutoDAO produtoDAO = new ProdutoDAO();
    private final FornecedorDAO fornecedorDAO = new FornecedorDAO();

    /**
     * Creates new form DialogVend
     */
    public DialogCadProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtCategoria.setEnabled(false);
        cbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarCampoCategoria();
            }
        });
        carregarCategorias();
        carregarFornecedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        panelIdProduto = new javax.swing.JPanel();
        labelCodProduto = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        txtNomeproduto = new javax.swing.JTextField();
        labelCategoria = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txtValCompra = new javax.swing.JTextField();
        labelValCompra = new javax.swing.JLabel();
        labelValVenda = new javax.swing.JLabel();
        txtValVenda = new javax.swing.JTextField();
        labelFornecedor = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        labelQtd = new javax.swing.JLabel();
        spinnerQtd = new javax.swing.JSpinner();
        txtCategoria = new javax.swing.JTextField();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelCodProduto.setText("Cód. Produto");

        labelNome.setText("Nome Produto");

        labelCategoria.setText("Categoria");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Valores"));

        labelValCompra.setText("Valor Compra R$");

        labelValVenda.setText("Valor Venda R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(labelValCompra))
                    .addComponent(txtValCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelValVenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelValCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        labelFornecedor.setText("Fornecedor");

        cmbFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>());

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        labelQtd.setText("Quantidade");

        spinnerQtd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spinnerQtd.setName(""); // NOI18N
        spinnerQtd.setRequestFocusEnabled(false);

        txtCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIdProdutoLayout = new javax.swing.GroupLayout(panelIdProduto);
        panelIdProduto.setLayout(panelIdProdutoLayout);
        panelIdProdutoLayout.setHorizontalGroup(
            panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(labelQtd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinnerQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdProdutoLayout.createSequentialGroup()
                        .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCategoria))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdProdutoLayout.createSequentialGroup()
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))
                    .addGroup(panelIdProdutoLayout.createSequentialGroup()
                        .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                                .addComponent(labelCodProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIdProdutoLayout.createSequentialGroup()
                                .addGap(0, 10, Short.MAX_VALUE)
                                .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome))
                        .addGap(55, 55, 55))
                    .addGroup(panelIdProdutoLayout.createSequentialGroup()
                        .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                                .addComponent(btnSalvar)
                                .addGap(7, 7, 7)
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar))
                            .addComponent(labelFornecedor))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelIdProdutoLayout.setVerticalGroup(
            panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIdProdutoLayout.createSequentialGroup()
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodProduto)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIdProdutoLayout.createSequentialGroup()
                        .addComponent(labelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(labelFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQtd)
                    .addComponent(spinnerQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(panelIdProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        String nome = txtNomeproduto.getText() == null ? "" : txtNomeproduto.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o nome do produto.");
            return;
        }

        String categoriaNome = obterNomeCategoriaSelecionada();
        if (categoriaNome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a categoria.");
            return;
        }

        Double preco = parseDecimal(txtValVenda.getText());
        if (preco == null || preco < 0) {
            JOptionPane.showMessageDialog(this, "Informe um valor de venda valido.");
            return;
        }

        int quantidade = obterQuantidade();
        if (quantidade < 0) {
            JOptionPane.showMessageDialog(this, "Informe uma quantidade valida.");
            return;
        }

        Fornecedor fornecedor = (Fornecedor) cmbFornecedor.getSelectedItem();
        if (fornecedor == null) {
            JOptionPane.showMessageDialog(this, "Informe o fornecedor.");
            return;
        }

        Categoria categoria = (Categoria) categoriaDAO.buscarPorCampoExato(Categoria.class, "nomeCategoria", categoriaNome);
        if (categoria == null) {
            categoria = new Categoria();
            categoria.setNomeCategoria(categoriaNome);
            categoria.setDescricao("");
        }

        Produto produto = new Produto();
        produto.setNomeProduto(nome);
        produto.setPreco(preco);
        produto.setQtdEstoque(quantidade);
        produto.setCat(categoria);
        produto.setFornecedor(fornecedor);

        try {
            produtoDAO.salvar(produto);
            JOptionPane.showMessageDialog(this, "Produto salvo com sucesso.");
            limparCamposProduto();
        } catch (RuntimeException ex) {
            logger.log(Level.SEVERE, "Falha ao salvar produto", ex);
            JOptionPane.showMessageDialog(this, "Falha ao salvar produto: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCamposProduto();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCategoriaActionPerformed
        // Sem acao.
    }//GEN-LAST:event_txtCategoriaActionPerformed

    private void carregarCategorias() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        boolean outroJaExiste = false;

        try {
            List<Categoria> categorias = categoriaDAO.listar();
            for (Categoria categoria : categorias) {
                String nome = categoria.getNomeCategoria();
                if (nome == null) {
                    continue;
                }
                String normalizado = nome.trim();
                if (normalizado.isEmpty()) {
                    continue;
                }
                if (normalizado.equalsIgnoreCase(CATEGORIA_OUTRO)) {
                    outroJaExiste = true;
                }
                model.addElement(normalizado);
            }
        } catch (RuntimeException ex) {
            logger.log(Level.WARNING, "Falha ao carregar categorias", ex);
        }

        if (!outroJaExiste) {
            model.addElement(CATEGORIA_OUTRO);
        }

        cbCategoria.setModel(model);
        if (model.getSize() == 1) {
            cbCategoria.setSelectedItem(CATEGORIA_OUTRO);
        } else if (model.getSize() > 0) {
            cbCategoria.setSelectedIndex(0);
        }
        atualizarCampoCategoria();
    }

    private void carregarFornecedores() {
        DefaultComboBoxModel<Fornecedor> model = new DefaultComboBoxModel<>();
        try {
            List<Fornecedor> fornecedores = fornecedorDAO.listar();
            for (Fornecedor fornecedor : fornecedores) {
                model.addElement(fornecedor);
            }
        } catch (RuntimeException ex) {
            logger.log(Level.WARNING, "Falha ao carregar fornecedores", ex);
        }

        cmbFornecedor.setModel(model);
        if (model.getSize() > 0) {
            cmbFornecedor.setSelectedIndex(0);
        }
    }

    private void atualizarCampoCategoria() {
        boolean outroSelecionado = isOutroSelecionado();
        txtCategoria.setEnabled(outroSelecionado);
        if (!outroSelecionado) {
            txtCategoria.setText("");
        }
    }

    private boolean isOutroSelecionado() {
        Object selected = cbCategoria.getSelectedItem();
        if (selected == null) {
            return false;
        }
        String value = selected.toString().trim();
        return value.equalsIgnoreCase(CATEGORIA_OUTRO);
    }

    private String obterNomeCategoriaSelecionada() {
        Object selected = cbCategoria.getSelectedItem();
        String value = selected == null ? "" : selected.toString().trim();
        if (value.isEmpty()) {
            return "";
        }
        if (value.equalsIgnoreCase(CATEGORIA_OUTRO)) {
            String nova = txtCategoria.getText() == null ? "" : txtCategoria.getText().trim();
            return nova;
        }
        return value;
    }

    private Double parseDecimal(String value) {
        String text = value == null ? "" : value.trim();
        if (text.isEmpty()) {
            return null;
        }
        String normalized = text.replace(" ", "");
        if (normalized.contains(",") && normalized.contains(".")) {
            normalized = normalized.replace(".", "").replace(",", ".");
        } else {
            normalized = normalized.replace(",", ".");
        }
        try {
            return Double.parseDouble(normalized);
        } catch (NumberFormatException ex) {
            return null;
        }
    }

    private int obterQuantidade() {
        Object value = spinnerQtd.getValue();
        if (value instanceof Number) {
            return ((Number) value).intValue();
        }
        try {
            return Integer.parseInt(String.valueOf(value));
        } catch (NumberFormatException ex) {
            return -1;
        }
    }

    private void limparCamposProduto() {
        txtCodProduto.setText("");
        txtNomeproduto.setText("");
        txtValCompra.setText("");
        txtValVenda.setText("");
        txtCategoria.setText("");
        spinnerQtd.setValue(0);
        carregarCategorias();
        carregarFornecedores();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<Fornecedor> cmbFornecedor;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCodProduto;
    private javax.swing.JLabel labelFornecedor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelQtd;
    private javax.swing.JLabel labelValCompra;
    private javax.swing.JLabel labelValVenda;
    private javax.swing.JPanel panelIdProduto;
    private javax.swing.JSpinner spinnerQtd;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtNomeproduto;
    private javax.swing.JTextField txtValCompra;
    private javax.swing.JTextField txtValVenda;
    // End of variables declaration//GEN-END:variables
}
