/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 2024122760121
 */
public class FramePrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipal.class.getName());

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new javax.swing.JMenuBar();
        menuVenda = new javax.swing.JMenu();
        menuProduto = new javax.swing.JMenuItem();
        menuFornecedores = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuEntrada = new javax.swing.JMenuItem();
        menuSaida = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuVenda.setText("Cadastro");

        menuProduto.setText("Produto");
        menuVenda.add(menuProduto);

        menuFornecedores.setText("Fornecedores");
        menuVenda.add(menuFornecedores);

        menuBar1.add(menuVenda);

        menuEstoque.setText("Venda");

        menuEntrada.setText("Entrada");
        menuEstoque.add(menuEntrada);

        menuSaida.setText("Saída");
        menuEstoque.add(menuSaida);

        menuBar1.add(menuEstoque);

        menuRelatorio.setText("Relatórios");
        menuBar1.add(menuRelatorio);

        jMenu1.setText("Listagem");
        menuBar1.add(jMenu1);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuItem menuEntrada;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuFornecedores;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuSaida;
    private javax.swing.JMenu menuVenda;
    // End of variables declaration//GEN-END:variables
}
