/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.ControlerInterface;

public class FramePrincipal extends javax.swing.JFrame {
    private ControlerInterface controlInterface;
    
    public FramePrincipal(ControlerInterface controlerInterface) {
        controlInterface = controlerInterface;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadProduto = new javax.swing.JMenuItem();
        menuCadFornecedores = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuEntrada = new javax.swing.JMenuItem();
        menuSaida = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menuListagem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuCadastro.setText("Cadastro");

        menuCadProduto.setText("Produto");
        menuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProdutoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadProduto);

        menuCadFornecedores.setText("Fornecedores");
        menuCadFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedoresActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadFornecedores);

        menuBar1.add(menuCadastro);

        menuEstoque.setText("Venda");

        menuEntrada.setText("Entrada");
        menuEstoque.add(menuEntrada);

        menuSaida.setText("Saída");
        menuEstoque.add(menuSaida);

        menuBar1.add(menuEstoque);

        menuRelatorio.setText("Relatórios");
        menuBar1.add(menuRelatorio);

        menuListagem.setText("Listagem");
        menuBar1.add(menuListagem);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProdutoActionPerformed
        // TODO add your handling code here:
        controlInterface.abrirDialogCadProduto();
    }//GEN-LAST:event_menuCadProdutoActionPerformed

    private void menuCadFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedoresActionPerformed
        // TODO add your handling code here:
        controlInterface.abrirDialogCadFornecedores();
    }//GEN-LAST:event_menuCadFornecedoresActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenuItem menuCadFornecedores;
    private javax.swing.JMenuItem menuCadProduto;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem menuEntrada;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenu menuListagem;
    private javax.swing.JMenu menuRelatorio;
    private javax.swing.JMenuItem menuSaida;
    // End of variables declaration//GEN-END:variables
}
